### ISSUE TITLE
How to set up project? (And thanks from the dev community)

### ISSUE THREAD

**Issue by codekey-admin** [johan-akerman/Greet#24]
Hi Johan! I've been following your progress in Greet and I'm sorry to hear the project is no longer under development.

Could you please post a final update or answer this issue explaining how to run the project? I tried adding my Firebase variables to a .env.local but I just don't understand how to run the admin page (To post jobs, etc.)

My sincere thanks in advance and congratulations on the project! Greetings from Norway! <3

**Comment by johan-akerman** [comment]
Hello! I am glad to hear that you have followed Greet. I will try to post more details in the readme in the upcoming days / week.

// Johan

**Comment by codekey-admin** [comment]
Thanks Johan! Really looking forward to knowing how to set up the project for companies / admin login, I will be waiting for it :)

**Comment by johan-akerman** [comment]
Hello again, 
For this project, getting company access is "hard coded" and manually achieved inside of Firebase. The reason behind this is that companies should only be added under supervision.

Once you have set up your own firebase environment and have created a new user on the website, you need to manually create a document inside the "companies" collection on firebase and you need to name that collection to the USER UID for the user who you want to be the admin for that company (see image below). 

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/44551216/169087256-25dcb183-452d-4c52-973f-256b31837fdf.png">

You can find the USER UID for your users under the "authentication" tab inside firebase. Keep in mind that this setup is not ideal, it is just a solution i quickly developed to get the site up and running!

Hope this helps,
// Johan

**Comment by codekey-admin** [comment]
Worked for me! Thank you so much for your time and patience Johan. Greet is such an awesome project!
